import http from 'http';
import crypto from 'crypto';
import os from 'os';
import { WebSocket, WebSocketServer } from 'ws';
import { REMOTE_CONTROL_PAGE } from './remoteControlPage';
import { logError } from './logger';

// The compact live-match snapshot pushed to every paired phone: enough for the
// mobile page to render the score, clock, on-air screen, and team labels, and
// nothing else. Kept intentionally small (never the full app state) so a phone
// on the LAN only ever sees what the remote can already control.
export interface RemoteControlSnapshot {
  scores: { homeTeam: number; awayTeam: number };
  time: { time?: string; paused?: boolean; matchPhase?: string };
  matchState: { displayScreen: string; matchPhase?: string };
  matchSettings: {
    homeTeamNameAbbreviated: string;
    awayTeamNameAbbreviated: string;
    homeTeamNameFull: string;
    awayTeamNameFull: string;
  };
}

// The only command intents a paired phone may send. Commands are intents, not
// state: the phone says "homeGoal", the app decides what the score becomes.
// `setScreen` is the one command that carries a payload (the target screen id),
// validated against the served page's known screen ids in parseRemoteCommand.
export const REMOTE_COMMAND_TYPES = [
  'homeGoal',
  'awayGoal',
  'homeGoalRemove',
  'awayGoalRemove',
  'nextPhase',
  'toggleClock',
  'setScreen',
] as const;

export type RemoteCommandType = (typeof REMOTE_COMMAND_TYPES)[number];

export interface RemoteCommand {
  type: RemoteCommandType;
  // Only present (and required) for `setScreen`.
  screen?: string;
}

// The screen ids the remote is allowed to switch to. Mirrors the built-in
// screens in constants.ts minus `custom` (which needs an image the phone has
// no way to pick) and duplicated here rather than imported so this module
// stays a self-contained, Electron-free unit that the page and its validation
// can be reasoned about in one place.
export const REMOTE_SCREEN_IDS = [
  'none',
  'matchTitle',
  'scoreBug',
  'penalties',
  'endScreen',
  'scoreboard',
] as const;

export interface StartRemoteControlServerOptions {
  port: number;
  // The 6-digit pairing PIN for this run. Regenerated by main.ts on every
  // (re)start, so a fresh PIN is required after each enable.
  pin: string;
  getSnapshot: () => RemoteControlSnapshot;
  onCommand: (command: RemoteCommand) => void;
  // Fired whenever the number of paired phones changes (a pair succeeds or a
  // paired socket closes), so the settings UI can show a live count.
  onConnectionChange?: (connectedCount: number) => void;
  // Overridable for tests; see HEARTBEAT_INTERVAL_MS.
  heartbeatIntervalMs?: number;
}

export type StartRemoteControlServerResult =
  { ok: true } | { ok: false; error: string };

// Phones can't observe protocol-level ping frames from a WebSocket, so the
// server sends an application-level heartbeat on this interval to feed the
// page's liveness watchdog while no match data is flowing. Mirrors the browser
// source's heartbeat; the page tolerates a couple of missed beats before it
// tears down and reconnects.
const HEARTBEAT_INTERVAL_MS = 15000;

// A phone that fails to pair this many times is refused further attempts for
// PAIRING_COOLDOWN_MS, and any burst of this many failures across all sockets
// within the same window trips the same global cooldown. A 6-digit PIN has a
// million combinations; throttling to a handful of guesses per 30 seconds
// turns a brute-force from seconds into years, while a legitimate operator who
// simply mistypes once or twice is never meaningfully delayed.
const MAX_PAIRING_FAILURES = 5;
const PAIRING_COOLDOWN_MS = 30000;

// Pairing/command frames are tiny JSON objects. Anything larger is not
// something this protocol ever sends, so it's dropped unread rather than
// parsed, so a hostile client can't make the main process allocate on a huge
// buffer.
const MAX_MESSAGE_BYTES = 4096;

// Constant-time PIN comparison. crypto.timingSafeEqual requires equal-length
// buffers (and throws otherwise, which would itself leak length via the error
// path), so both sides are hashed to a fixed 32 bytes first: the comparison is
// then length-independent and still constant-time, and unequal PINs (including
// empty or wrong-length ones) simply produce unequal digests.
export function constantTimeEqual(a: string, b: string): boolean {
  const hashA = crypto.createHash('sha256').update(String(a)).digest();
  const hashB = crypto.createHash('sha256').update(String(b)).digest();
  return crypto.timingSafeEqual(hashA, hashB);
}

// Validates a decoded client message against the command allowlist, returning
// the typed command or null. Pure and Electron-free so it's unit-testable in
// isolation: unknown/missing types are rejected, and `setScreen` must carry a
// recognised screen id (an unknown screen would otherwise set the display to a
// bogus value). Never trusts anything beyond {type} (and {screen} for
// setScreen); extra fields on the wire are ignored.
export function parseRemoteCommand(raw: unknown): RemoteCommand | null {
  if (!raw || typeof raw !== 'object') return null;
  const type = (raw as { type?: unknown }).type;
  if (
    typeof type !== 'string' ||
    !(REMOTE_COMMAND_TYPES as readonly string[]).includes(type)
  ) {
    return null;
  }

  if (type === 'setScreen') {
    const screen = (raw as { screen?: unknown }).screen;
    if (
      typeof screen !== 'string' ||
      !(REMOTE_SCREEN_IDS as readonly string[]).includes(screen)
    ) {
      return null;
    }
    return { type, screen };
  }

  return { type: type as RemoteCommandType };
}

// The first non-internal IPv4 address from a set of OS network interfaces,
// used only to build the http://<ip>:<port> URL shown to the operator (and its
// QR code). Pure so it's unit-testable against a mocked interface set; the
// os.networkInterfaces() read happens at the call site in main.ts. Node has
// reported interface `family` as both the string 'IPv4' and (newer versions)
// the number 4, so both are accepted.
export function getLanIPv4(
  interfaces: NodeJS.Dict<os.NetworkInterfaceInfo[]>
): string | null {
  for (const infos of Object.values(interfaces)) {
    if (!infos) continue;
    for (const info of infos) {
      const isIPv4 =
        info.family === 'IPv4' || (info.family as unknown as number) === 4;
      if (isIPv4 && !info.internal) {
        return info.address;
      }
    }
  }
  return null;
}

interface SocketMeta {
  paired: boolean;
  failedAttempts: number;
}

let server: http.Server | null = null;
let wss: WebSocketServer | null = null;
let heartbeatInterval: ReturnType<typeof setInterval> | null = null;
// Per-socket pairing/authorization state. A Map (not a property on the socket)
// keeps this module's bookkeeping separate from the ws instance.
const sockets = new Map<WebSocket, SocketMeta>();

// The PIN and callbacks for the currently running server. Captured on start so
// the connection/message handlers don't close over stale start options.
let currentPin = '';
let currentGetSnapshot: (() => RemoteControlSnapshot) | null = null;
let currentOnCommand: ((command: RemoteCommand) => void) | null = null;
let currentOnConnectionChange: ((connectedCount: number) => void) | null = null;

// Global pairing-failure bookkeeping (see MAX_PAIRING_FAILURES). Timestamps of
// recent failures within the cooldown window, plus the instant until which all
// pairing is refused once the threshold is tripped.
let pairingFailureTimestamps: number[] = [];
let pairingCooldownUntil = 0;

export function isRemoteControlServerRunning(): boolean {
  return server !== null;
}

export function getRemoteControlServerPort(): number | null {
  const address = server?.address();
  return address && typeof address === 'object' ? address.port : null;
}

export function getRemoteControlServerAddress(): string | null {
  const address = server?.address();
  return address && typeof address === 'object' ? address.address : null;
}

export function getRemoteControlConnectedCount(): number {
  let count = 0;
  sockets.forEach((meta) => {
    if (meta.paired) count += 1;
  });
  return count;
}

function safeSend(socket: WebSocket, message: unknown): void {
  if (socket.readyState !== WebSocket.OPEN) return;
  try {
    socket.send(JSON.stringify(message));
  } catch (error) {
    logError(`Remote control send error: ${String(error)}`);
  }
}

function notifyConnectionChange(): void {
  try {
    currentOnConnectionChange?.(getRemoteControlConnectedCount());
  } catch (error) {
    logError(
      `Remote control connection-change handler error: ${String(error)}`
    );
  }
}

function sendSnapshot(socket: WebSocket): void {
  if (!currentGetSnapshot) return;
  try {
    safeSend(socket, { type: 'state', payload: currentGetSnapshot() });
  } catch (error) {
    logError(`Error sending remote control snapshot: ${String(error)}`);
  }
}

// Handles a {type:'pair', pin} frame. Enforces the cooldown first (so a
// tripped brute-force lockout skips the comparison entirely), then does a
// constant-time PIN check. On success the socket is marked paired and gets an
// immediate state snapshot; on failure the per-socket and global counters are
// advanced and the cooldown is armed once either threshold is reached.
function handlePairAttempt(
  socket: WebSocket,
  meta: SocketMeta,
  pin: unknown
): void {
  const now = Date.now();

  if (now < pairingCooldownUntil) {
    safeSend(socket, { type: 'unauthorized' });
    return;
  }

  if (typeof pin === 'string' && constantTimeEqual(pin, currentPin)) {
    meta.paired = true;
    meta.failedAttempts = 0;
    safeSend(socket, { type: 'paired' });
    sendSnapshot(socket);
    notifyConnectionChange();
    return;
  }

  meta.failedAttempts += 1;
  pairingFailureTimestamps.push(now);
  pairingFailureTimestamps = pairingFailureTimestamps.filter(
    (timestamp) => now - timestamp < PAIRING_COOLDOWN_MS
  );

  if (
    meta.failedAttempts >= MAX_PAIRING_FAILURES ||
    pairingFailureTimestamps.length >= MAX_PAIRING_FAILURES
  ) {
    pairingCooldownUntil = now + PAIRING_COOLDOWN_MS;
  }

  safeSend(socket, { type: 'unauthorized' });
}

function handleMessage(
  socket: WebSocket,
  meta: SocketMeta,
  data: Buffer
): void {
  // Drop anything larger than a pairing/command frame unread.
  if (data.length > MAX_MESSAGE_BYTES) return;

  let message: unknown;
  try {
    message = JSON.parse(data.toString());
  } catch {
    return;
  }
  if (!message || typeof message !== 'object') return;

  const type = (message as { type?: unknown }).type;

  if (type === 'pair') {
    handlePairAttempt(socket, meta, (message as { pin?: unknown }).pin);
    return;
  }

  // Commands are only ever honoured from a paired socket. Anything sent before
  // a successful pair (a command, a stray frame) is silently ignored, so an
  // unpaired client can never drive the match.
  if (!meta.paired) return;

  const command = parseRemoteCommand(message);
  if (!command) return;

  try {
    currentOnCommand?.(command);
  } catch (error) {
    logError(`Remote control command handler error: ${String(error)}`);
  }
}

// Binds an http+ws server to 0.0.0.0 (all interfaces) so a phone on the same
// LAN can reach it, unlike the browser source which is 127.0.0.1-only.
// Resolves `{ ok: false, error }` on any startup error (e.g. EADDRINUSE)
// instead of throwing, so a bad port can never crash the app.
export function startRemoteControlServer(
  opts: StartRemoteControlServerOptions
): Promise<StartRemoteControlServerResult> {
  if (server) {
    return Promise.resolve({
      ok: false,
      error: 'Remote control server is already running',
    });
  }

  return new Promise((resolve) => {
    const httpServer = http.createServer((req, res) => {
      try {
        handleHttpRequest(req, res);
      } catch (error) {
        // A request must never take down the main process.
        logError(`Remote control request error: ${String(error)}`);
        if (!res.headersSent) {
          res.writeHead(400);
        }
        res.end('Bad request');
      }
    });

    const onError = (error: NodeJS.ErrnoException) => {
      httpServer.removeAllListeners();
      resolve({ ok: false, error: error.message ?? String(error) });
    };

    const onListening = () => {
      httpServer.removeListener('error', onError);
      server = httpServer;
      currentPin = opts.pin;
      currentGetSnapshot = opts.getSnapshot;
      currentOnCommand = opts.onCommand;
      currentOnConnectionChange = opts.onConnectionChange ?? null;
      // A fresh server run starts with a clean pairing slate: a cooldown from a
      // previous run must not carry over into a newly enabled server.
      pairingFailureTimestamps = [];
      pairingCooldownUntil = 0;

      wss = new WebSocketServer({ server: httpServer });
      wss.on('connection', (socket) => {
        // Every socket starts UNPAIRED. It must send a valid {type:'pair', pin}
        // before any command it sends is honoured.
        const meta: SocketMeta = { paired: false, failedAttempts: 0 };
        sockets.set(socket, meta);
        socket.on('message', (data) =>
          handleMessage(socket, meta, data as Buffer)
        );
        socket.on('close', () => {
          const wasPaired = sockets.get(socket)?.paired ?? false;
          sockets.delete(socket);
          if (wasPaired) notifyConnectionChange();
        });
        socket.on('error', (error) => {
          logError(`Remote control socket error: ${String(error)}`);
        });
      });

      // Runtime errors after a successful bind must not crash the app either.
      httpServer.on('error', (error) => {
        logError(`Remote control server error: ${String(error)}`);
      });

      heartbeatInterval = setInterval(() => {
        if (!wss) return;
        const message = JSON.stringify({ type: 'heartbeat' });
        wss.clients.forEach((client) => {
          if (client.readyState === WebSocket.OPEN) {
            client.send(message);
          }
        });
      }, opts.heartbeatIntervalMs ?? HEARTBEAT_INTERVAL_MS);

      resolve({ ok: true });
    };

    httpServer.once('error', onError);
    httpServer.once('listening', onListening);
    httpServer.listen(opts.port, '0.0.0.0');
  });
}

// Serves the single self-contained mobile control page at any GET path. There
// are no other routes and no static files on disk, so there is no path to
// traverse: every request returns the same in-memory page (built into the main
// bundle as a string), and non-GET requests are refused.
function handleHttpRequest(
  req: http.IncomingMessage,
  res: http.ServerResponse
): void {
  if (req.method && req.method !== 'GET' && req.method !== 'HEAD') {
    res.writeHead(405, { Allow: 'GET, HEAD' });
    res.end('Method not allowed');
    return;
  }
  res.writeHead(200, {
    'Content-Type': 'text/html; charset=utf-8',
    // The page controls a live match; never let a stale copy linger in a
    // phone's cache across app restarts (a new PIN each run).
    'Cache-Control': 'no-store',
  });
  res.end(REMOTE_CONTROL_PAGE);
}

// Resolves once the underlying socket is actually released, so a caller that
// immediately restarts on the same port (a settings change) doesn't race the
// OS into a transient EADDRINUSE. Mirrors stopBrowserSourceServer.
export function stopRemoteControlServer(): Promise<void> {
  if (heartbeatInterval) {
    clearInterval(heartbeatInterval);
    heartbeatInterval = null;
  }
  sockets.forEach((_meta, socket) => socket.terminate());
  sockets.clear();
  wss?.close();
  wss = null;
  currentGetSnapshot = null;
  currentOnCommand = null;
  currentOnConnectionChange = null;
  currentPin = '';

  const serverToClose = server;
  server = null;
  if (!serverToClose) return Promise.resolve();

  return new Promise((resolve) => {
    serverToClose.close(() => resolve());
  });
}

// Pushes the current match snapshot to every paired phone. Unpaired sockets
// (still on the PIN screen) are skipped, so state is only ever sent to a client
// that has authenticated.
export function broadcastRemoteControlState(
  snapshot: RemoteControlSnapshot
): void {
  if (!wss) return;
  const message = JSON.stringify({ type: 'state', payload: snapshot });
  sockets.forEach((meta, socket) => {
    if (meta.paired && socket.readyState === WebSocket.OPEN) {
      socket.send(message);
    }
  });
}
