import http from 'http';
import crypto from 'crypto';
import os from 'os';
import { WebSocket, WebSocketServer } from 'ws';
import {
  REMOTE_CONTROL_PAGE,
  REMOTE_HEARTBEAT_INTERVAL_MS,
} from './remoteControlPage';
import { logError } from './logger';

// The compact live-match snapshot pushed to every paired phone: enough for the
// mobile page to render the score, clock, on-air screen, and team labels, and
// nothing else. Kept intentionally small (never the full app state) so a phone
// on the LAN only ever sees what the remote can already control.
export interface RemoteControlSnapshot {
  scores: { homeTeam: number; awayTeam: number };
  time: { time?: string; paused?: boolean; matchPhase?: string };
  matchState: { displayScreen: string; matchPhase?: string };
  matchSettings: {
    homeTeamNameAbbreviated: string;
    awayTeamNameAbbreviated: string;
    homeTeamNameFull: string;
    awayTeamNameFull: string;
  };
}

// The only command intents a paired phone may send. Commands are intents, not
// state: the phone says "homeGoal", the app decides what the score becomes.
// `setScreen` is the one command that carries a payload (the target screen id),
// validated against the served page's known screen ids in parseRemoteCommand.
export const REMOTE_COMMAND_TYPES = [
  'homeGoal',
  'awayGoal',
  'homeGoalRemove',
  'awayGoalRemove',
  'nextPhase',
  'toggleClock',
  'setScreen',
] as const;

export type RemoteCommandType = (typeof REMOTE_COMMAND_TYPES)[number];

export interface RemoteCommand {
  type: RemoteCommandType;
  // Only present (and required) for `setScreen`.
  screen?: string;
}

// The screen ids the remote is allowed to switch to. Mirrors the built-in
// screens in constants.ts minus `custom` (which needs an image the phone has
// no way to pick) and duplicated here rather than imported so this module
// stays a self-contained, Electron-free unit that the page and its validation
// can be reasoned about in one place.
export const REMOTE_SCREEN_IDS = [
  'none',
  'matchTitle',
  'scoreBug',
  'penalties',
  'endScreen',
  'scoreboard',
] as const;

export interface StartRemoteControlServerOptions {
  port: number;
  // The 6-digit pairing PIN for this run. Regenerated by main.ts on every
  // (re)start, so a fresh PIN is required after each enable.
  pin: string;
  getSnapshot: () => RemoteControlSnapshot;
  onCommand: (command: RemoteCommand) => void;
  // Fired whenever the number of paired phones changes (a pair succeeds or a
  // paired socket closes), so the settings UI can show a live count.
  onConnectionChange?: (connectedCount: number) => void;
  // Overridable for tests; see HEARTBEAT_INTERVAL_MS.
  heartbeatIntervalMs?: number;
}

export type StartRemoteControlServerResult =
  { ok: true } | { ok: false; error: string };

// Phones can't observe protocol-level ping frames from a WebSocket, so the
// server sends an application-level heartbeat on this interval to feed the
// page's liveness watchdog while no match data is flowing. The page gives up
// on a socket after about two and a half missed beats, so this interval
// bounds how long a half-open connection can pass for "Connected" (a phone
// that walked out of Wi-Fi range, a laptop that slept) while the operator's
// taps are silently lost. The value lives in the page module so the page's
// watchdog is derived from the same number.
const HEARTBEAT_INTERVAL_MS = REMOTE_HEARTBEAT_INTERVAL_MS;

// The server also pings every socket at the heartbeat interval (browsers
// answer ws pings automatically) and terminates one that misses this many
// pongs in a row, so a phone that vanished stops counting towards the
// settings UI's connected count within a few seconds instead of whenever the
// OS finally times the TCP connection out.
const MAX_MISSED_PONGS = 2;

// An address (one device on the LAN) that fails to pair this many times within
// PAIRING_COOLDOWN_MS is refused further PIN attempts for PAIRING_COOLDOWN_MS.
// A 6-digit PIN has a million combinations; throttling each device to a
// handful of guesses per 30 seconds turns a brute-force from seconds into
// years, while an operator who mistypes once or twice is never delayed. The
// throttle is per address, not global, so a misbehaving device can only lock
// itself out, never the operator's phone.
const MAX_PAIRING_FAILURES = 5;
const PAIRING_COOLDOWN_MS = 30000;

// Upper bound on the number of addresses the pairing throttle tracks at once,
// so a stream of connections from many addresses can't grow its map without
// limit. Far beyond any real venue LAN; see PairingThrottle for eviction.
const MAX_TRACKED_ADDRESSES = 256;

// Upper bound on live resume tokens per server run (one per successful PIN
// pairing). Only a handful of phones ever pair, so evicting the oldest past
// this cap never affects a real operator.
const MAX_RESUME_TOKENS = 64;

// A resume token is 32 random bytes, base64url-encoded (43 characters).
// Anything longer on the wire is not a token this server issued.
const MAX_RESUME_TOKEN_LENGTH = 128;

// Pairing/command frames are tiny JSON objects. Anything larger is not
// something this protocol ever sends. The WebSocketServer's maxPayload
// enforces this while frames are still arriving (ws closes the connection),
// so an unpaired client on the LAN can't make the main process buffer a huge
// message; handleMessage re-checks it before parsing as a second line.
const MAX_MESSAGE_BYTES = 4096;

// Constant-time PIN comparison. crypto.timingSafeEqual requires equal-length
// buffers (and throws otherwise, which would itself leak length via the error
// path), so both sides are hashed to a fixed 32 bytes first: the comparison is
// then length-independent and still constant-time, and unequal PINs (including
// empty or wrong-length ones) simply produce unequal digests.
export function constantTimeEqual(a: string, b: string): boolean {
  const hashA = crypto.createHash('sha256').update(String(a)).digest();
  const hashB = crypto.createHash('sha256').update(String(b)).digest();
  return crypto.timingSafeEqual(hashA, hashB);
}

// Validates a decoded client message against the command allowlist, returning
// the typed command or null. Pure and Electron-free so it's unit-testable in
// isolation: unknown/missing types are rejected, and `setScreen` must carry a
// recognised screen id (an unknown screen would otherwise set the display to a
// bogus value). Never trusts anything beyond {type} (and {screen} for
// setScreen); extra fields on the wire are ignored.
export function parseRemoteCommand(raw: unknown): RemoteCommand | null {
  if (!raw || typeof raw !== 'object') return null;
  const type = (raw as { type?: unknown }).type;
  if (
    typeof type !== 'string' ||
    !(REMOTE_COMMAND_TYPES as readonly string[]).includes(type)
  ) {
    return null;
  }

  if (type === 'setScreen') {
    const screen = (raw as { screen?: unknown }).screen;
    if (
      typeof screen !== 'string' ||
      !(REMOTE_SCREEN_IDS as readonly string[]).includes(screen)
    ) {
      return null;
    }
    return { type, screen };
  }

  return { type: type as RemoteCommandType };
}

// One reachable-looking IPv4 address the phone URL could use, as ranked by
// getLanIPv4Candidates. `isPrivate` means an RFC 1918 home/office range;
// `isLikelyVirtual` means the adapter looks like a VM, container, or VPN
// interface rather than the machine's real Wi-Fi or Ethernet.
export interface LanAddressCandidate {
  address: string;
  interfaceName: string;
  isPrivate: boolean;
  isLikelyVirtual: boolean;
}

// Adapter names that belong to hypervisors, containers, WSL, and VPN/overlay
// networks rather than the network a phone is on. Short Unix-style names are
// matched as prefixes (vmnet8, docker0, br-1a2b, utun3, wg0, ztabc123), longer
// Windows-style friendly names anywhere in the name ("vEthernet (WSL)",
// "VirtualBox Host-Only Network", "VMware Network Adapter VMnet1").
const VIRTUAL_INTERFACE_PREFIX =
  /^(vmnet|vboxnet|docker|br-|veth|virbr|lxc|lxd|cni|flannel|podman|utun|tun|tap|wg|zt|ipsec|ppp|gif|stf|bridge|awdl|llw|anpi)/i;
const VIRTUAL_INTERFACE_SUBSTRING =
  /(vethernet|virtualbox|vmware|hyper-v|wsl|docker|tailscale|zerotier|wireguard|openvpn|nordlynx|vpn|virtual|loopback|pseudo|tap-windows)/i;

// MAC address prefixes (OUIs) assigned to virtual NICs. Windows lets a user
// rename an adapter to "Ethernet 2", but a Hyper-V or VirtualBox adapter
// keeps its vendor prefix, so this catches renamed virtual adapters too.
const VIRTUAL_MAC_PREFIXES = [
  '00:15:5d', // Hyper-V (including WSL's vEthernet)
  '08:00:27', // VirtualBox guest NICs
  '0a:00:27', // VirtualBox host-only adapters on the host
  '00:05:69', // VMware
  '00:0c:29', // VMware
  '00:1c:14', // VMware
  '00:50:56', // VMware
  '02:42:', // Docker bridges and containers
];

function parseIPv4(address: string): number[] | null {
  const parts = address.split('.');
  if (parts.length !== 4) return null;
  const octets = parts.map((part) => Number(part));
  if (octets.some((octet) => !Number.isInteger(octet) || octet < 0)) {
    return null;
  }
  return octets;
}

function isPrivateIPv4([a, b]: number[]): boolean {
  return (
    a === 10 || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168)
  );
}

function isLikelyVirtualInterface(
  name: string,
  info: os.NetworkInterfaceInfo,
  octets: number[]
): boolean {
  if (VIRTUAL_INTERFACE_PREFIX.test(name)) return true;
  if (VIRTUAL_INTERFACE_SUBSTRING.test(name)) return true;
  const mac = (info.mac ?? '').toLowerCase();
  if (VIRTUAL_MAC_PREFIXES.some((prefix) => mac.startsWith(prefix))) {
    return true;
  }
  // VirtualBox's default host-only network. A real LAN almost never uses
  // this exact /24, and ranking it lower is harmless when one does: it is
  // still offered as a candidate.
  const [a, b, c] = octets;
  return a === 192 && b === 168 && c === 56;
}

// Every IPv4 address a phone could plausibly reach this machine on, best
// first, for the http://<ip>:<port> URL shown to the operator (and its QR
// code). Pure so it's unit-testable against a mocked interface set; the
// os.networkInterfaces() read happens at the call site in main.ts.
//
// Picking the first non-internal address is wrong surprisingly often on a
// streaming PC: Windows lists WSL/Hyper-V "vEthernet", VirtualBox host-only,
// and VPN adapters alongside (and frequently before) the real Wi-Fi, and a
// machine whose DHCP failed only has a 169.254.x.x link-local address. So:
// loopback, link-local, and unspecified addresses are dropped entirely, and
// the rest are ranked private-on-a-real-adapter first, then public or other
// ranges on a real adapter (a venue network might use one), then anything on
// a virtual adapter. Order within a rank follows the OS listing, which puts
// the primary interface first on every mainstream platform.
//
// Node has reported interface `family` as both the string 'IPv4' and (newer
// versions) the number 4, so both are accepted.
export function getLanIPv4Candidates(
  interfaces: NodeJS.Dict<os.NetworkInterfaceInfo[]>
): LanAddressCandidate[] {
  const candidates: (LanAddressCandidate & { rank: number; order: number })[] =
    [];
  for (const [interfaceName, infos] of Object.entries(interfaces)) {
    if (!infos) continue;
    for (const info of infos) {
      const isIPv4 =
        info.family === 'IPv4' || (info.family as unknown as number) === 4;
      if (!isIPv4 || info.internal) continue;
      const octets = parseIPv4(info.address);
      if (!octets) continue;
      const [a, b] = octets;
      // Unspecified, loopback (should already be internal), and link-local
      // (APIPA: DHCP failed, nothing else on the LAN is on this range).
      if (a === 0 || a === 127 || (a === 169 && b === 254)) continue;

      const isPrivate = isPrivateIPv4(octets);
      const isLikelyVirtual = isLikelyVirtualInterface(
        interfaceName,
        info,
        octets
      );
      const rank = (isLikelyVirtual ? 2 : 0) + (isPrivate ? 0 : 1);
      candidates.push({
        address: info.address,
        interfaceName,
        isPrivate,
        isLikelyVirtual,
        rank,
        order: candidates.length,
      });
    }
  }
  return candidates
    .sort((left, right) => left.rank - right.rank || left.order - right.order)
    .map(({ address, interfaceName, isPrivate, isLikelyVirtual }) => ({
      address,
      interfaceName,
      isPrivate,
      isLikelyVirtual,
    }));
}

// The single best LAN IPv4 address (see getLanIPv4Candidates), or null when
// the machine has no usable external IPv4 address at all.
export function getLanIPv4(
  interfaces: NodeJS.Dict<os.NetworkInterfaceInfo[]>
): string | null {
  return getLanIPv4Candidates(interfaces)[0]?.address ?? null;
}

// Whether a WebSocket upgrade's Origin header is acceptable. The control page
// is served by this same server, so a real phone's upgrade always carries an
// Origin whose host:port equals the Host it connected to. Any other web page
// (on any LAN device, including the streaming PC's own browser) sends its own
// origin and is refused, so a malicious page can't drive the remote or burn
// through PIN guesses from inside a victim's browser. A missing Origin means a
// non-browser client (which could forge the header anyway), so it's allowed
// through to the PIN check like any other device.
export function isAllowedOrigin(
  origin: string | undefined,
  host: string | undefined
): boolean {
  if (origin === undefined) return true;
  if (!host) return false;
  try {
    return new URL(origin).host.toLowerCase() === host.toLowerCase();
  } catch {
    // Unparseable, or the literal "null" origin of a sandboxed or file://
    // page: neither is the served control page.
    return false;
  }
}

// Normalises a socket's remote address for the pairing throttle. A dual-stack
// socket can report an IPv4 peer as an IPv4-mapped IPv6 address, which must
// count as the same device as the plain dotted form.
function normaliseRemoteAddress(address: string | undefined): string {
  if (!address) return 'unknown';
  return address.startsWith('::ffff:') ? address.slice(7) : address;
}

interface AddressPairingState {
  // Timestamps of this address's recent failures within the window.
  failures: number[];
  // The instant until which this address's PIN attempts are refused.
  cooldownUntil: number;
}

export interface PairingThrottleOptions {
  maxFailures: number;
  windowMs: number;
  cooldownMs: number;
  maxTrackedAddresses: number;
}

// Per-address brute-force throttle for PIN pairing. Exported (and clock-free:
// every method takes `now`) so the lockout rules are unit-testable with
// arbitrary addresses, which a loopback-only test can't produce over real
// sockets.
//
// The map is bounded: when a new address arrives at the cap, entries whose
// failures and cooldown have both expired are pruned first, and if the map is
// still full the least recently failing address is evicted (Map iteration is
// insertion order, and every failure re-inserts its address at the end).
export class PairingThrottle {
  private readonly states = new Map<string, AddressPairingState>();

  constructor(private readonly options: PairingThrottleOptions) {}

  get trackedAddressCount(): number {
    return this.states.size;
  }

  // Milliseconds until `address` may try a PIN again, or 0 if it may now.
  cooldownRemainingMs(address: string, now: number): number {
    const state = this.states.get(address);
    if (!state) return 0;
    return Math.max(0, state.cooldownUntil - now);
  }

  // Records a wrong PIN from `address`. Returns the cooldown now in force for
  // it in milliseconds (0 when the failure didn't trip the threshold).
  recordFailure(address: string, now: number): number {
    const existing = this.states.get(address);
    if (existing) {
      this.states.delete(address);
    } else {
      this.makeRoom(now);
    }
    const state = existing ?? { failures: [], cooldownUntil: 0 };
    state.failures = state.failures.filter(
      (timestamp) => now - timestamp < this.options.windowMs
    );
    state.failures.push(now);
    if (state.failures.length >= this.options.maxFailures) {
      state.cooldownUntil = now + this.options.cooldownMs;
      // The cooldown itself is the penalty; start the next window afresh
      // so the address gets a full allowance once it expires.
      state.failures = [];
    }
    this.states.set(address, state);
    return Math.max(0, state.cooldownUntil - now);
  }

  // Forgets `address` entirely (a successful pairing from it).
  clear(address: string): void {
    this.states.delete(address);
  }

  reset(): void {
    this.states.clear();
  }

  private makeRoom(now: number): void {
    if (this.states.size < this.options.maxTrackedAddresses) return;
    for (const [address, state] of this.states) {
      const expired =
        now >= state.cooldownUntil &&
        state.failures.every(
          (timestamp) => now - timestamp >= this.options.windowMs
        );
      if (expired) this.states.delete(address);
    }
    if (this.states.size >= this.options.maxTrackedAddresses) {
      const oldest = this.states.keys().next().value;
      if (oldest !== undefined) this.states.delete(oldest);
    }
  }
}

interface SocketMeta {
  paired: boolean;
  // The normalised remote address this socket connected from, the key for
  // the pairing throttle.
  address: string;
  // Consecutive server pings this socket hasn't answered; see
  // MAX_MISSED_PONGS.
  missedPongs: number;
}

let server: http.Server | null = null;
let wss: WebSocketServer | null = null;
let heartbeatInterval: ReturnType<typeof setInterval> | null = null;
// Per-socket pairing/authorization state. A Map (not a property on the socket)
// keeps this module's bookkeeping separate from the ws instance.
const sockets = new Map<WebSocket, SocketMeta>();

// The PIN and callbacks for the currently running server. Captured on start so
// the connection/message handlers don't close over stale start options.
let currentPin = '';
let currentGetSnapshot: (() => RemoteControlSnapshot) | null = null;
let currentOnCommand: ((command: RemoteCommand) => void) | null = null;
let currentOnConnectionChange: ((connectedCount: number) => void) | null = null;

// Per-address pairing-failure bookkeeping (see MAX_PAIRING_FAILURES).
const pairingThrottle = new PairingThrottle({
  maxFailures: MAX_PAIRING_FAILURES,
  windowMs: PAIRING_COOLDOWN_MS,
  cooldownMs: PAIRING_COOLDOWN_MS,
  maxTrackedAddresses: MAX_TRACKED_ADDRESSES,
});

// SHA-256 digests of the resume tokens issued this server run, oldest first
// (Set iteration is insertion order, which the eviction relies on). Only
// digests are kept, so the lookup's timing reveals nothing useful about a
// token's characters, and the set is cleared on every start so a token never
// outlives the PIN it was earned with.
const resumeTokenDigests = new Set<string>();

export function isRemoteControlServerRunning(): boolean {
  return server !== null;
}

export function getRemoteControlServerPort(): number | null {
  const address = server?.address();
  return address && typeof address === 'object' ? address.port : null;
}

export function getRemoteControlServerAddress(): string | null {
  const address = server?.address();
  return address && typeof address === 'object' ? address.address : null;
}

export function getRemoteControlConnectedCount(): number {
  let count = 0;
  sockets.forEach((meta) => {
    if (meta.paired) count += 1;
  });
  return count;
}

function safeSend(socket: WebSocket, message: unknown): void {
  if (socket.readyState !== WebSocket.OPEN) return;
  try {
    socket.send(JSON.stringify(message));
  } catch (error) {
    logError(`Remote control send error: ${String(error)}`);
  }
}

function notifyConnectionChange(): void {
  try {
    currentOnConnectionChange?.(getRemoteControlConnectedCount());
  } catch (error) {
    logError(
      `Remote control connection-change handler error: ${String(error)}`
    );
  }
}

function sendSnapshot(socket: WebSocket): void {
  if (!currentGetSnapshot) return;
  try {
    safeSend(socket, { type: 'state', payload: currentGetSnapshot() });
  } catch (error) {
    logError(`Error sending remote control snapshot: ${String(error)}`);
  }
}

function digestResumeToken(token: string): string {
  return crypto.createHash('sha256').update(token).digest('hex');
}

// Mints a resume token for a socket that has just paired with the PIN. The
// page keeps it and presents it on every reconnect, so a phone recovering
// from a Wi-Fi blip re-pairs without the PIN (and without a PIN attempt that
// could count towards the throttle). 256 random bits: unguessable, so resume
// attempts need no throttling of their own.
function issueResumeToken(): string {
  const token = crypto.randomBytes(32).toString('base64url');
  resumeTokenDigests.add(digestResumeToken(token));
  if (resumeTokenDigests.size > MAX_RESUME_TOKENS) {
    const oldest = resumeTokenDigests.values().next().value;
    if (oldest !== undefined) resumeTokenDigests.delete(oldest);
  }
  return token;
}

// Marks a socket paired and sends it the ack (carrying its resume token)
// followed by an immediate state snapshot, which the page waits for before
// enabling its controls.
function completePairing(
  socket: WebSocket,
  meta: SocketMeta,
  token: string
): void {
  const wasPaired = meta.paired;
  meta.paired = true;
  safeSend(socket, { type: 'paired', token });
  sendSnapshot(socket);
  if (!wasPaired) notifyConnectionChange();
}

// Handles a {type:'pair', pin} frame. Enforces this address's cooldown first
// (so a tripped brute-force lockout skips the comparison entirely), then does
// a constant-time PIN check. On success the socket is paired and issued a
// resume token; on failure the address's counter is advanced and the reply
// says whether it is now cooling down, so the page can say "wrong PIN" or
// "wait N seconds" rather than a vague catch-all.
function handlePairAttempt(
  socket: WebSocket,
  meta: SocketMeta,
  pin: unknown
): void {
  const now = Date.now();

  const remainingMs = pairingThrottle.cooldownRemainingMs(meta.address, now);
  if (remainingMs > 0) {
    safeSend(socket, {
      type: 'unauthorized',
      reason: 'cooldown',
      retryAfterSeconds: Math.ceil(remainingMs / 1000),
    });
    return;
  }

  if (typeof pin === 'string' && constantTimeEqual(pin, currentPin)) {
    pairingThrottle.clear(meta.address);
    completePairing(socket, meta, issueResumeToken());
    return;
  }

  const cooldownMs = pairingThrottle.recordFailure(meta.address, now);
  safeSend(
    socket,
    cooldownMs > 0
      ? {
          type: 'unauthorized',
          reason: 'cooldown',
          retryAfterSeconds: Math.ceil(cooldownMs / 1000),
        }
      : { type: 'unauthorized', reason: 'wrongPin' }
  );
}

// Handles a {type:'resume', token} frame from a phone that paired earlier.
// A token from this server run re-pairs the socket (even while its address is
// cooling down: the token is proof it already knew the PIN). An unknown token,
// typically one from before the app or the remote server restarted with a new
// PIN, is not a PIN guess and never counts towards the throttle; the reply
// just tells the page to ask the operator for the new PIN.
function handleResumeAttempt(
  socket: WebSocket,
  meta: SocketMeta,
  token: unknown
): void {
  if (
    typeof token === 'string' &&
    token.length > 0 &&
    token.length <= MAX_RESUME_TOKEN_LENGTH &&
    resumeTokenDigests.has(digestResumeToken(token))
  ) {
    completePairing(socket, meta, token);
    return;
  }
  safeSend(socket, { type: 'unauthorized', reason: 'resumeRejected' });
}

function handleMessage(
  socket: WebSocket,
  meta: SocketMeta,
  data: Buffer
): void {
  // Drop anything larger than a pairing/command frame unread.
  if (data.length > MAX_MESSAGE_BYTES) return;

  let message: unknown;
  try {
    message = JSON.parse(data.toString());
  } catch {
    return;
  }
  if (!message || typeof message !== 'object') return;

  const type = (message as { type?: unknown }).type;

  if (type === 'pair') {
    handlePairAttempt(socket, meta, (message as { pin?: unknown }).pin);
    return;
  }

  if (type === 'resume') {
    handleResumeAttempt(socket, meta, (message as { token?: unknown }).token);
    return;
  }

  // Commands are only ever honoured from a paired socket. Anything sent before
  // a successful pair (a command, a stray frame) is silently ignored, so an
  // unpaired client can never drive the match.
  if (!meta.paired) return;

  const command = parseRemoteCommand(message);
  if (!command) return;

  try {
    currentOnCommand?.(command);
  } catch (error) {
    logError(`Remote control command handler error: ${String(error)}`);
  }
}

// Binds an http+ws server to 0.0.0.0 (all interfaces) so a phone on the same
// LAN can reach it, unlike the browser source which is 127.0.0.1-only.
// Resolves `{ ok: false, error }` on any startup error (e.g. EADDRINUSE)
// instead of throwing, so a bad port can never crash the app.
export function startRemoteControlServer(
  opts: StartRemoteControlServerOptions
): Promise<StartRemoteControlServerResult> {
  if (server) {
    return Promise.resolve({
      ok: false,
      error: 'Remote control server is already running',
    });
  }

  return new Promise((resolve) => {
    const httpServer = http.createServer((req, res) => {
      try {
        handleHttpRequest(req, res);
      } catch (error) {
        // A request must never take down the main process.
        logError(`Remote control request error: ${String(error)}`);
        if (!res.headersSent) {
          res.writeHead(400);
        }
        res.end('Bad request');
      }
    });

    const onError = (error: NodeJS.ErrnoException) => {
      httpServer.removeAllListeners();
      resolve({ ok: false, error: error.message ?? String(error) });
    };

    const onListening = () => {
      httpServer.removeListener('error', onError);
      server = httpServer;
      currentPin = opts.pin;
      currentGetSnapshot = opts.getSnapshot;
      currentOnCommand = opts.onCommand;
      currentOnConnectionChange = opts.onConnectionChange ?? null;
      // A fresh server run starts with a clean pairing slate: a cooldown from a
      // previous run must not carry over into a newly enabled server, and a
      // resume token earned with the previous run's PIN must not outlive it.
      pairingThrottle.reset();
      resumeTokenDigests.clear();

      wss = new WebSocketServer({
        server: httpServer,
        maxPayload: MAX_MESSAGE_BYTES,
        // Refuse cross-origin upgrades before a socket even exists (see
        // isAllowedOrigin). 403 rather than ws's default 401: no credential
        // would make this request acceptable.
        verifyClient: (info, callback) => {
          if (isAllowedOrigin(info.origin, info.req.headers.host)) {
            callback(true);
          } else {
            callback(false, 403, 'Forbidden');
          }
        },
      });
      wss.on('connection', (socket, req) => {
        // Every socket starts UNPAIRED. It must send a valid {type:'pair', pin}
        // or {type:'resume', token} before any command it sends is honoured.
        const meta: SocketMeta = {
          paired: false,
          address: normaliseRemoteAddress(req.socket.remoteAddress),
          missedPongs: 0,
        };
        sockets.set(socket, meta);
        socket.on('pong', () => {
          meta.missedPongs = 0;
        });
        socket.on('message', (data) =>
          handleMessage(socket, meta, data as Buffer)
        );
        socket.on('close', () => {
          const wasPaired = sockets.get(socket)?.paired ?? false;
          sockets.delete(socket);
          if (wasPaired) notifyConnectionChange();
        });
        socket.on('error', (error) => {
          logError(`Remote control socket error: ${String(error)}`);
        });
      });

      // Runtime errors after a successful bind must not crash the app either.
      httpServer.on('error', (error) => {
        logError(`Remote control server error: ${String(error)}`);
      });

      heartbeatInterval = setInterval(() => {
        if (!wss) return;
        const message = JSON.stringify({ type: 'heartbeat' });
        sockets.forEach((meta, socket) => {
          if (socket.readyState !== WebSocket.OPEN) return;
          // Unanswered pings mean the phone is gone without a FIN (out of
          // range, asleep). Terminating fires 'close', which drops it from
          // the connected count; the page will resume with its token.
          if (meta.missedPongs >= MAX_MISSED_PONGS) {
            socket.terminate();
            return;
          }
          meta.missedPongs += 1;
          try {
            socket.ping();
            socket.send(message);
          } catch (error) {
            logError(`Remote control heartbeat error: ${String(error)}`);
          }
        });
      }, opts.heartbeatIntervalMs ?? HEARTBEAT_INTERVAL_MS);

      resolve({ ok: true });
    };

    httpServer.once('error', onError);
    httpServer.once('listening', onListening);
    httpServer.listen(opts.port, '0.0.0.0');
  });
}

// Serves the single self-contained mobile control page at any GET path. There
// are no other routes and no static files on disk, so there is no path to
// traverse: every request returns the same in-memory page (built into the main
// bundle as a string), and non-GET requests are refused.
function handleHttpRequest(
  req: http.IncomingMessage,
  res: http.ServerResponse
): void {
  if (req.method && req.method !== 'GET' && req.method !== 'HEAD') {
    res.writeHead(405, { Allow: 'GET, HEAD' });
    res.end('Method not allowed');
    return;
  }
  res.writeHead(200, {
    'Content-Type': 'text/html; charset=utf-8',
    // The page controls a live match; never let a stale copy linger in a
    // phone's cache across app restarts (a new PIN each run).
    'Cache-Control': 'no-store',
  });
  res.end(REMOTE_CONTROL_PAGE);
}

// Resolves once the underlying socket is actually released, so a caller that
// immediately restarts on the same port (a settings change) doesn't race the
// OS into a transient EADDRINUSE. Mirrors stopBrowserSourceServer.
export function stopRemoteControlServer(): Promise<void> {
  if (heartbeatInterval) {
    clearInterval(heartbeatInterval);
    heartbeatInterval = null;
  }
  sockets.forEach((_meta, socket) => socket.terminate());
  sockets.clear();
  wss?.close();
  wss = null;
  currentGetSnapshot = null;
  currentOnCommand = null;
  currentOnConnectionChange = null;
  currentPin = '';
  resumeTokenDigests.clear();
  pairingThrottle.reset();

  const serverToClose = server;
  server = null;
  if (!serverToClose) return Promise.resolve();

  return new Promise((resolve) => {
    serverToClose.close(() => resolve());
  });
}

// Pushes the current match snapshot to every paired phone. Unpaired sockets
// (still on the PIN screen) are skipped, so state is only ever sent to a client
// that has authenticated.
export function broadcastRemoteControlState(
  snapshot: RemoteControlSnapshot
): void {
  if (!wss) return;
  const message = JSON.stringify({ type: 'state', payload: snapshot });
  sockets.forEach((meta, socket) => {
    if (meta.paired && socket.readyState === WebSocket.OPEN) {
      socket.send(message);
    }
  });
}
